import numpy as np

dt_Future = np.dtype([
    ('chWindCode', np.str_, 32),
    ('chCode', np.str_, 32),
    ('nDate', np.int32),
    ('nTime', np.int32),
    ('iVolume', np.int64),
    ('iTurover', np.int64),
    ('nSettle', np.int32),
    ('nPosition', np.int32),
    ('nCurDelta', np.int32),
    ('chTradeFlag', np.str_, 1),
    ('iAccVolume', np.int64),
    ('iAccTurover', np.int64),
    ('nHigh', np.int32),
    ('nLow', np.int32),
    ('nOpen', np.int32),
    ('nPrice', np.int32),
    ('nPreClose', np.int32),
    ('nPreSettle', np.int32),
    ('nPrePosition', np.int32)
    ])

dt_FutureAB = np.dtype([
    ('chWindCode', np.str_, 32),
    ('chCode', np.str_, 32),
    ('nDate', np.int32),
    ('nTime', np.int32),
    ('iVolume', np.int64),
    ('iTurover', np.int64),
    ('nSettle', np.int32),
    ('nPosition', np.int32),
    ('nCurDelta', np.int32),
    ('chTradeFlag', np.str_, 1),
    ('iAccVolume', np.int64),
    ('iAccTurover', np.int64),
    ('nOpen', np.int32),
    ('nHigh', np.int32),
    ('nLow', np.int32),
    ('nPrice', np.int32),
    ('nAskPrice', np.int32, 5),
    ('nAskVolume', np.int32, 5),
    ('nBidPrice', np.int32, 5),
    ('nBidVolume', np.int32, 5),
    ('nPreClose', np.int32),
    ('nPreSettle', np.int32),
    ('nPrePosition', np.int32),
    ])

dt_OrderQueue = np.dtype([
    ('chWindCode', np.str_, 32),
    ('chCode', np.str_, 32),
    ('nDate', np.int32),
    ('nTime', np.int32),
    ('nSide', np.int32),
    ('nPrice', np.int32),
    ('nOrderItems', np.int32),
    ('nABItems', np.int32),
    ('nABVolume', np.int32, 50)
    ])

dt_TickAB = np.dtype([
    ('chWindCode', np.str_, 32),
    ('chCode', np.str_, 32),
    ('nDate', np.int32),
    ('nTime', np.int32),
    ('nPrice', np.int32),
    ('iVolume', np.int64),
    ('iTurover', np.int64),
    ('nMatchItems', np.int32),
    ('nInterest', np.int32),
    ('chTradeFlag', np.str_, 1),
    ('chBSFlag', np.str_, 1),
    ('iAccVolume', np.int64),
    ('iAccTurover', np.int64),
    ('nHigh', np.int32),
    ('nLow', np.int32),
    ('nOpen', np.int32),
    ('nPreClose', np.int32),
    ('nAskPrice', np.int32, 10),
    ('nAskVolume', np.uint32, 10),
    ('nBidPrice', np.int32, 10),
    ('nBidVolume', np.uint32, 10),
    ('nAskAvPrice', np.int32),
    ('nBidAvPrice', np.int32),
    ('iTotalAskVolume', np.int64),
    ('iTotalBidVolume', np.int64),
    ('nIndex', np.int32),
    ('nStocks', np.int32),
    ('nUps', np.int32),
    ('nDowns', np.int32),
    ('nHoldLines', np.int32)
    ])

dt_Transaction = np.dtype([
    ('chWindCode', np.str_, 32),
    ('chCode', np.str_, 32),
    ('nDate', np.int32),
    ('nTime', np.int32),
    ('nIndex', np.int32),
    ('chFunctionCode', np.str_, 1),
    ('chOrderKind', np.str_, 1),
    ('chBSFlag', np.str_, 1),
    ('nTradePrice', np.int32),
    ('nTradeVolume', np.int32),
    ('nAskOrder', np.int32),
    ('nBidOrder', np.int32)
    ])
